### ISSUE TITLE
Latest release "stop" issue, crash??

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/ADLMIDI-Player-Java#3]
The latest version plays a midi but immediately the GUI is removed and I'm sent to my home launcher, with the dialog "ADLMIDI Player has stopped". The midi plays as the dialog is shown, but stops when I dismiss the dialog.

I've never seen an Android app do this! I can listen to the midi as long as the screen is on and the dialog is displayed, but as soon as either one turns off the midi stops. :(

**Comment by Wohlstand** [comment]
Which MIDI file you have tried to play, which device specs you have? (Android version and CPU)
I need to analyze this...

**Comment by sneakernets** [comment]
I tried to play "rasputin.mid" from your site. and I have a Galaxy Note 9 North America edition with Android 8.0, Snapdragon 845 2.8 GHz

**Comment by Wohlstand** [comment]
Checked that out, and on my device that file is playing fine with no crash (Samsung Galaxy S 3, Arm32, Android 4.3). Gonna to try the ARM64 simulator with Android 8.0...

**Comment by Wohlstand** [comment]
Anyway, quick question: does previous release or even pre-previous also crashing?

**Comment by sneakernets** [comment]
1.2.0.3 does *not* crash.

**Comment by sneakernets** [comment]
1.4 and 1.4.1 crash for me. :(

**Comment by Wohlstand** [comment]
Looks some side of OpenSL ES or the difference of SDK / NDK that was used to build each version... Tomorrow I'll try to make a build on older SDK/NDK for a test...
The big difference of 1.2/1.3 and 1.4 that I have finally made a proper foreground service that will don't die while you surfing other apps.

**Comment by Wohlstand** [comment]
EDIT: Oh, do you mean a crash happens when you switching different application or clearing memory? So yeah, it's probably not matter to cpu but matter Android 8.0 I must to check...

Looks the daemon ran, but Java prt side

**Comment by sneakernets** [comment]
I'm going to download android studio this week and try to compile it myself and see what happens. Maybe that will give me some debug information.

**Comment by Wohlstand** [comment]
Yeah, Android Studio is that needed, and inside it you need to install NDK and CMake (Inside of SDK Manager)

**Comment by Wohlstand** [comment]
Anyway, at evening I'll give a second shot to run on Android 8.0 locally in parallel...

**Comment by Wohlstand** [comment]
@sneakernets , I have tried to debug this and I have found on Android 8 it's now required to have the "Notification Channel" to be able show the service box. I did the fix for you:
[ADLMIDI-Player-release.apk.zip](https://github.com/Wohlstand/ADLMIDI-Player-Java/files/2503675/ADLMIDI-Player-release.apk.zip)
Please try out this and report, does this fixes Android 8 on your end or not?

EDIT: And the similar fix was made for OPNMIDI too: [OPNMIDI-Player-release.apk.zip](https://github.com/Wohlstand/ADLMIDI-Player-Java/files/2503766/OPNMIDI-Player-release.apk.zip)

**Comment by sneakernets** [comment]
I will test this after my meeting today! thank you!

**Comment by sneakernets** [comment]
This worked! Thank you! It doesn't crash anymore on my Note 9.

**Comment by Wohlstand** [comment]
On my end the app didn't crashed on the emulator with Android 8.0, but didn't spawned any notifications (in the logcat I have found it was failed to find notification channel).

**Comment by Wohlstand** [comment]
So, I'm glad it works now, therefore I will close this! :wink:

**Comment by farvardin** [comment]
Your latest version fixed the crash on my android 8 phone (pocophone f1), but with latest update to android 9, now it's crashing again when playing a midi file...

**Comment by Wohlstand** [comment]
Never tested 9th... But looks like another API feature that requires change...

**Comment by Wohlstand** [comment]
I have tried to run at my job for quick test, and the next error was happen:
```
2019-02-04 12:02:13.617 1911-2036/? W/ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService } to com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService from pid=12570 uid=10063 pkg=com.google.android.apps.messaging startFg?=false
2019-02-04 12:02:13.619 12570-12570/? W/BugleDataModel: ActionExecutorImpl: Action started execution, but we can't guarantee it will complete, the app may be killed. Action: class com.google.android.apps.messaging.shared.datamodel.action.FixupMessageStatusOnStartupAction-FixupMessageStatusOnStartupAction:1549270927582001
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService }: app is in background uid UidRecord{b9a5ab6 u0a63 CEM  idle change:cached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:91)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:22)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:17)
        at djq.c(SourceFile:12)
        at djr.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-02-04 12:02:13.620 1911-2036/? W/ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService } to com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService from pid=12570 uid=10063 pkg=com.google.android.apps.messaging startFg?=false
2019-02-04 12:02:13.621 12570-12570/? W/BugleDataModel: ActionExecutorImpl: Action started execution, but we can't guarantee it will complete, the app may be killed. Action: class com.google.android.apps.messaging.shared.datamodel.action.ProcessPendingMessagesAction-ProcessPendingMessagesAction:1549270927582002
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService }: app is in background uid UidRecord{b9a5ab6 u0a63 CEM  idle change:cached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:91)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:22)
        at com.google.android.apps.messaging.shared.datamodel.action.execution.ActionExecutorImpl.a(SourceFile:17)
        at djq.c(SourceFile:12)
        at djr.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

And first that I have googled: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten
https://stackoverflow.com/questions/49961273/java-lang-illegalstateexception-not-allowed-to-start-service-intent-while-tryin
Will try some...

**Comment by Wohlstand** [comment]
@farvardin , I have made a test build, please check it out:
[ADLMIDI-Player-1.4.2.1-dev.apk.zip](https://github.com/Wohlstand/ADLMIDI-Player-Java/files/2827292/ADLMIDI-Player-1.4.2.1-dev.apk.zip)
I'll apply same fix to OPNMIDI for Android too at my home. :wink: :fox_face:

**Comment by farvardin** [comment]
It works!!!!
You're the boss! Thank you!
